# kubectl apply -f helm/cron_jobs/gossipqa-txn-burst-cronjob.yaml
# the above command, with this accompanying file, needs only be run once.  it does not get run in CI.  this file is provided here for future reference
# make sure you're in the gossipqa namespace
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gossipqa-txn-burst-cronjob
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - '
printf "/dns4/seed-1.gossipqa.o1test.net/tcp/10000/p2p/12D3KooWLpjCfeBWdiVRG3mqRS5ixfPQpF4gRJooFiXMa8wGpt1A\n/dns4/seed-2.gossipqa.o1test.net/tcp/10001/p2p/12D3KooWS5MQzph8pjCQ9uvjhzsEDos5P8rysBFR673Hs4UrnwTc" > /gossipqa_seed_list.txt;

echo "booting mina daemon";
mina daemon --config-file /config/daemon.json --generate-genesis-proof true --peer-list-file /gossipqa_seed_list.txt --background;
sleep 480;
echo "done sleeping";
while true; do
  STATUS=$(mina client status | grep "Sync status");
  echo "$STATUS" | grep "Synced";
  RESULT=$?;
  if [ $RESULT -eq 0 ]; then
    echo "daemon is synced";
    break;
  else
    echo "waiting for daemon to sync";
    sleep 60;
  fi;
done;


mkdir /tmpkeys;
chmod 700 /tmpkeys;

cp /keys/whale-key1/online-whale-account-1-key /tmpkeys;
chmod 600 /tmpkeys/online-whale-account-1-key;
cp /keys/whale-key2/online-whale-account-2-key /tmpkeys;
chmod 600 /tmpkeys/online-whale-account-2-key;

./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe gen-there-and-back-txns --num-txn-per-acct 100 --rate-limit-level 1 --rate-limit-interval 5000 --origin-sender-sk-path "/tmpkeys/online-whale-account-1-key" --origin-sender-sk-pw "naughty blue worm" --returner-sk-path "/tmpkeys/online-whale-account-2-key" --returner-sk-pw "naughty blue worm";

echo "ran batch txns";

            '
            
            env:
            - name: MINA_PRIVKEY_PASS
              value: ""
            - name: GCLOUD_KEYFILE
              value: /gcloud/keyfile.json
            image: gcr.io/o1labs-192920/mina-txn-burst-app@sha256:8c4a7e0c092dcdbe0f5d8bebefb374181012dfb08e7cd60f99ee88969f1b26e8
            imagePullPolicy: IfNotPresent
            name: gossipqa-txn-burst-cronjob
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /keys/whale-key1/
              name: whale-key1
            - mountPath: /keys/whale-key2/
              name: whale-key2
            - mountPath: /config
              name: daemon-config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes: [
            {
              "name":"daemon-config",
              "configMap": {
                "name": "seed-daemon-config"
              }
            },
            {
              "name": "whale-key1",
              "secret": {
                "defaultMode": 0600,
                "items": [
                  {
                    "key": "key",
                    "path": "online-whale-account-1-key"
                  },
                  {
                    "key": "pub",
                    "path": "online-whale-account-1-key.pub"
                  }
                ],
                "secretName": "online-whale-account-1-key"
              }
            },
            {
              "name": "whale-key2",
              "secret": {
                "defaultMode": 0600,
                "items": [
                  {
                    "key": "key",
                    "path": "online-whale-account-2-key"
                  },
                  {
                    "key": "pub",
                    "path": "online-whale-account-2-key.pub"
                  }
                ],
                "secretName": "online-whale-account-2-key"
              }
            }

          ]
  schedule: 0 13 * * * 
  # every day at 1pm GMT, which is 6am PST
  successfulJobsHistoryLimit: 3
  suspend: false
